CREATE ROLE IF NOT EXISTS app_role;
GRANT USAGE ON WAREHOUSE CONTAINER_WAREHOUSE TO ROLE app_role;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE app_role;
GRANT USAGE, MONITOR ON COMPUTE POOL CONTAINER_COMPUTE_POOL TO ROLE app_role;
GRANT USAGE ON DATABASE learning_db TO ROLE app_role;
GRANT USAGE ON SCHEMA learning_db.dw TO ROLE app_role;
GRANT SELECT ON ALL TABLES IN SCHEMA learning_db.dw TO ROLE app_role;
GRANT SELECT ON ALL VIEWS IN SCHEMA learning_db.dw TO ROLE app_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA learning_db.dw TO ROLE app_role;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA learning_db.dw TO ROLE app_role;


CREATE USER IF NOT EXISTS app_user
    DEFAULT_ROLE = app_role
    DEFAULT_WAREHOUSE = CONTAINER_WAREHOUSE
    TYPE = SERVICE
    COMMENT = 'User account for testing snowflake apps';

GRANT ROLE app_role TO USER app_user;